stages:
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: flask_hello:v1
      pushRemote: true
      registry: 127.0.0.1:34383
timeout: 60
notification: {}
