stages:
- name: build image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: flask_hello:v1
      registry: index.docker.io
    when:
      branch: {}
timeout: 60
notification: {}
